#!/usr/bin/env bash
# Installs nginx web server

apt-get update
apt-get install -y nginx
echo "hello world!" > /etc/nginx/html/index.html
echo "server {
    listen 80;
    listen [::]:80 default_server;
    root   /etc/nginx/html;
    index  index.html;
    location /redirect_me {
        return 301 https://https://www.google.com/
    }
}" > /etc/nginx/sites-available/default
service nginx restart
