#!/usr/bin/env bash

# Update package list
sudo apt-get update &&

# Install Nginx if not already installed
sudo apt-get install -y nginx &&

# Update Nginx configuration to use port 80
sudo sed -i 's/8080/80/g' /etc/nginx/sites-enabled/default &&

# Restart Nginx
sudo service nginx restart
