#!/usr/bin/env bash
# Define the server hostname or IP address
server="8.8.8.8"

# Define the path to the private key file
private_key="~/.ssh/school"

# Use SSH with single-character flags to connect
ssh -i "~/.ssh/codingschool" "ubuntu@8.8.8.8"
