#!/usr/bin/env bash
# uses ssh to connect to server using a private key
# Define the server's hostname or IP address
server="8.8.8.8"

# Define the path to the private key file
private_key="~/.ssh/school"

# Use SSH with single-character flags to connect
ssh -i "~/.ssh/school" "ubuntu@8.8.8.8"
